import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const vazirFont = localFont({
  src: '../public/fonts/Vazirmatn-Medium.ttf'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`w-full h-screen bg-slate-900 text-slate-200 ${vazirFont.className}`}>
        <main className='px-8 py-6'>
          {children}
        </main>
      </body>
    </html>
  );
}
